version: '3.3'
networks:
  default:

services:
  web:
    container_name: automations
    build: .
    image: automations
    ports:
      - 5000:5000
    env_file:
       - .env

  mongo:
    container_name: mongo_stocks
    image: mongo:3.4-jessie
    ports:
      - 27017:27017